# Generated by Django 5.2.3 on 2025-06-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client'),
        ),
    ]
